### ISSUE TITLE
fas and far, not "fa" now

### ISSUE THREAD

**Issue by alain01** [geekwright/xswatch4#9]
https://fontawesome.com/

The fa prefix has been deprecated in version 5. The new default is the fas solid style and the fab style for brands.

**Comment by geekwright** [comment]
Fontawesome update is not in scope for XOOPS 2.5.11.

**Comment by alain01** [comment]
Yes, but for V4, fas and fab yet work.
So it's better to use the good prefix for V5, so it's ready when XOOPS will use v5.

I missed something ?

**Comment by geekwright** [comment]
It is hard to debug a control for visuals that you can't see. Fontawesome is widely used inside of XOOPS, so the switch to v5 will require some analysis and any changes are best left to the time when we are implementing it. Leaving it in as v4's "fa" only will make it much easier to identify the work to be done and tested.

Honestly, looking at the competing products, fontawesome may not be the clear choice in the near future. We'll see.

**Comment by alain01** [comment]
Ok, thank you for your clear explanation, Richard.
